'''
default_fits: nominal_fits
'''
#counts
MULTICOLLECT_COUNTS= 600

#baselines
BASELINE_COUNTS= 180
BASELINE_DETECTOR= 'H1'
BASELINE_MASS= 39.5
BASELINE_BEFORE= False
BASELINE_AFTER= True
BASELINE_SETTLING_TIME= 15

#peak center
PEAK_CENTER_BEFORE= False
PEAK_CENTER_AFTER= True
PEAK_CENTER_DETECTOR= 'H1'
PEAK_CENTER_ISOTOPE= 'Ar40'
PEAK_DETECTORS= ('H1','AX','CDD')

#equilibration
EQ_TIME= 8.0
INLET= 'R'
OUTLET= 'O'
EQ_DELAY= 3.0

ACTIVE_DETECTORS=('H2','H1','AX','L1','L2','CDD')
